dist: xenial
language: python
jobs:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9-dev"
install:
- python3 -m pip install pydiatra pyflakes
script:
- ./irssilogs < /dev/null
- python3 -m pydiatra .
- python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
